insert into pets (customer_id, name) values (1, 'Brolga crane');
insert into pets (customer_id, name) values (1, 'Bear, sloth');
insert into pets (customer_id, name) values (1, 'Ovenbird');
insert into pets (customer_id, name) values (1, 'Pademelon, red-legged');
insert into pets (customer_id, name) values (1, 'Nilgai');
insert into pets (customer_id, name) values (1, 'Black-fronted bulbul');
insert into pets (customer_id, name) values (1, 'White-necked raven');
insert into pets (customer_id, name) values (1, 'Dabchick');
insert into pets (customer_id, name) values (1, 'Marten, american');
insert into pets (customer_id, name) values (1, 'Sun gazer');
insert into pets (customer_id, name) values (1, 'Bat, asian false vampire');
insert into pets (customer_id, name) values (1, 'Gonolek, burchell''s');
insert into pets (customer_id, name) values (1, 'Woodpecker, downy');
insert into pets (customer_id, name) values (1, 'Squirrel, golden-mantled ground');
insert into pets (customer_id, name) values (1, 'River wallaby');
insert into pets (customer_id, name) values (1, 'Lourie, grey');
insert into pets (customer_id, name) values (1, 'South American sea lion');
insert into pets (customer_id, name) values (1, 'Squirrel, eurasian red');
insert into pets (customer_id, name) values (1, 'Owl, white-browed');
insert into pets (customer_id, name) values (1, 'Finch, common melba');
insert into pets (customer_id, name) values (1, 'Suricate');
insert into pets (customer_id, name) values (1, 'Pine squirrel');
insert into pets (customer_id, name) values (1, 'Brush-tailed phascogale');
insert into pets (customer_id, name) values (1, 'Gull, pacific');
insert into pets (customer_id, name) values (1, 'Seal, harbor');
insert into pets (customer_id, name) values (1, 'Lapwing (unidentified)');
insert into pets (customer_id, name) values (1, 'Ringtail');
insert into pets (customer_id, name) values (1, 'Otter, brazilian');
insert into pets (customer_id, name) values (1, 'Flamingo, chilean');
insert into pets (customer_id, name) values (1, 'Eastern indigo snake');
insert into pets (customer_id, name) values (1, 'Rabbit, eastern cottontail');
insert into pets (customer_id, name) values (1, 'Fowl, helmeted guinea');
insert into pets (customer_id, name) values (1, 'Marine iguana');
insert into pets (customer_id, name) values (1, 'Vulture, black');
insert into pets (customer_id, name) values (1, 'Raven, cape');
insert into pets (customer_id, name) values (1, 'Sandpiper, spotted wood');
insert into pets (customer_id, name) values (1, 'Sally lightfoot crab');
insert into pets (customer_id, name) values (1, 'Dove, laughing');
insert into pets (customer_id, name) values (1, 'Bear');
insert into pets (customer_id, name) values (1, 'Possum, common brushtail');